CREATE TABLE grupo_permissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    descricao VARCHAR(255)
);

CREATE TABLE grupo_permissao_item (
    grupo_id BIGINT NOT NULL REFERENCES grupo_permissao (id),
    permissao VARCHAR(255)
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    permissao VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL,
    grupo_id BIGINT REFERENCES grupo_permissao (id)
);

CREATE TABLE animal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    registro VARCHAR(255),
    raca VARCHAR(255),
    sexo VARCHAR(255),
    data_nascimento DATE,
    pelagem VARCHAR(255),
    modalidade_marcha VARCHAR(255),
    criador VARCHAR(255),
    proprietario VARCHAR(255),
    descricao VARCHAR(1000),
    imagem_principal VARCHAR(255),
    pai_id BIGINT REFERENCES animal (id),
    mae_id BIGINT REFERENCES animal (id)
);

CREATE TABLE leilao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    subtitulo VARCHAR(255),
    local VARCHAR(255),
    data_inicio TIMESTAMP(6) NOT NULL,
    data_fim TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE lote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leilao_id BIGINT NOT NULL REFERENCES leilao (id),
    numero INTEGER NOT NULL,
    nome_animal VARCHAR(255) NOT NULL,
    sexo VARCHAR(255),
    raca VARCHAR(255),
    idade_anos INTEGER,
    pelagem VARCHAR(255),
    registro VARCHAR(255),
    descricao_curta VARCHAR(500),
    descricao_oferta VARCHAR(500),
    lance_inicial NUMERIC(12, 2) NOT NULL,
    valor_reserva NUMERIC(12, 2)
);

CREATE TABLE lance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id BIGINT NOT NULL REFERENCES lote (id),
    usuario_id BIGINT NOT NULL REFERENCES usuario (id),
    valor NUMERIC(12, 2) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP(6) NOT NULL
);
